[workspace]
members = [
    "cargo:upki",
    "dist:dist-packages/libupki",
    "dist:dist-packages/libupki_openssl",
]

[dist]
cargo-dist-version = "0.32.0"
ci = "github"
installers = []
github-build-setup = "../cargo-c-setup.yml"
targets = [
    "aarch64-apple-darwin",
    "aarch64-unknown-linux-gnu",
    "aarch64-pc-windows-msvc",
    "x86_64-unknown-linux-gnu",
    "x86_64-unknown-linux-musl",
    "x86_64-pc-windows-msvc",
]
