name: upki-mirror
title: upki-mirror
summary: Fetch CRLite filters from Mozilla
description: |
  The "server-side" component of upki that fetches CRLite filters from
  Mozilla, such that they can be served using a standard web-server.

# Get the version dynamically from the built binary
adopt-info: upki-mirror

license: Apache-2.0
contact: https://github.com/rustls/upki/issues
issues: https://github.com/rustls/upki/issues
source-code: https://github.com/rustls/upki
website: https://github.com/rustls/upki

base: core24
confinement: strict
grade: stable
compression: lzo

apps:
  upki-mirror:
    command: bin/upki-mirror
    plugs:
      - home
      - network
      - removable-media

  daemon:
    command: bin/upki-mirror $SNAP_COMMON/data
    command-chain:
      - bin/create-dir
    daemon: simple
    # Start daemon at install time
    install-mode: enable
    # Run daily at 3 AM (See https://snapcraft.io/docs/timer-string-format)
    timer: 03:00
    plugs:
      - network

parts:
  upki-mirror:
    plugin: rust
    source: https://github.com/rustls/upki.git
    # We should replace this with source-tag when a release is cut.
    source-commit: 097c70611ebc09119f27f6d4deb5d8553080e56b
    source-subdir: upki-mirror
    override-pull: |
      craftctl default
      craftctl set version="$(git rev-parse --short HEAD)"

  create-dir:
    plugin: dump
    source-type: local
    source: snap/local
    organize:
      create-dir: bin/create-dir
